const countryCodes = [
  { country: "Afghanistan", flag: "🇦🇫" },
  { country: "Albania", flag: "🇦🇱" },
  { country: "Algeria", flag: "🇩🇿" },
  { country: "American Samoa", flag: "🇦🇸" },
  { country: "Andorra", flag: "🇦🇩" },
  { country: "Angola", flag: "🇦🇴" },
  { country: "Anguilla", flag: "🇦🇮" },
  { country: "Antigua and Barbuda", flag: "🇦🇬" },
  { country: "Argentina", flag: "🇦🇷" },
  { country: "Armenia", flag: "🇦🇲" },
  { country: "Aruba", flag: "🇦🇼" },
  { country: "Australia", flag: "🇦🇺" },
  { country: "Austria", flag: "🇦🇹" },
  { country: "Azerbaijan", flag: "🇦🇿" },
  { country: "Bahamas", flag: "🇧🇸" },
  { country: "Bahrain", flag: "🇧🇭" },
  { country: "Bangladesh", flag: "🇧🇩" },
  { country: "Barbados", flag: "🇧🇧" },
  { country: "Belarus", flag: "🇧🇾" },
  { country: "Belgium", flag: "🇧🇪" },
  { country: "Belize", flag: "🇧🇿" },
  { country: "Benin", flag: "🇧🇯" },
  { country: "Bermuda", flag: "🇧🇲" },
  { country: "Bhutan", flag: "🇧🇹" },
  { country: "Bolivia", flag: "🇧🇴" },
  { country: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { country: "Botswana", flag: "🇧🇼" },
  { country: "Brazil", flag: "🇧🇷" },
  { country: "British Virgin Islands", flag: "🇻🇬" },
  { country: "Brunei", flag: "🇧🇳" },
  { country: "Bulgaria", flag: "🇧🇬" },
  { country: "Burkina Faso", flag: "🇧🇫" },
  { country: "Burundi", flag: "🇧🇮" },
  { country: "Cambodia", flag: "🇰🇭" },
  { country: "Cameroon", flag: "🇨🇲" },
  { country: "Canada", flag: "🇨🇦" },
  { country: "Cape Verde", flag: "🇨🇻" },
  { country: "Cayman Islands", flag: "🇰🇾" },
  { country: "Central African Republic", flag: "🇨🇫" },
  { country: "Chad", flag: "🇹🇩" },
  { country: "Chile", flag: "🇨🇱" },
  { country: "China", flag: "🇨🇳" },
  { country: "Colombia", flag: "🇨🇴" },
  { country: "Comoros", flag: "🇰🇲" },
  { country: "Congo", flag: "🇨🇬" },
  { country: "Democratic Republic of the Congo", flag: "🇨🇩" },
  { country: "Cook Islands", flag: "🇨🇰" },
  { country: "Costa Rica", flag: "🇨🇷" },
  { country: "Côte d'Ivoire", flag: "🇨🇮" },
  { country: "Croatia", flag: "🇭🇷" },
  { country: "Cuba", flag: "🇨🇺" },
  { country: "Cyprus", flag: "🇨🇾" },
  { country: "Czech Republic", flag: "🇨🇿" },
  { country: "Denmark", flag: "🇩🇰" },
  { country: "Djibouti", flag: "🇩🇯" },
  { country: "Dominica", flag: "🇩🇲" },
  { country: "Dominican Republic", flag: "🇩🇴" },
  { country: "Ecuador", flag: "🇪🇨" },
  { country: "Egypt", flag: "🇪🇬" },
  { country: "El Salvador", flag: "🇸🇻" },
  { country: "Equatorial Guinea", flag: "🇬🇶" },
  { country: "Eritrea", flag: "🇪🇷" },
  { country: "Estonia", flag: "🇪🇪" },
  { country: "Ethiopia", flag: "🇪🇹" },
  { country: "Fiji", flag: "🇫🇯" },
  { country: "Finland", flag: "🇫🇮" },
  { country: "France", flag: "🇫🇷" },
  { country: "Germany", flag: "🇩🇪" },
  { country: "Ghana", flag: "🇬🇭" },
  { country: "Greece", flag: "🇬🇷" },
  { country: "Greenland", flag: "🇬🇱" },
  { country: "Grenada", flag: "🇬🇩" },
  { country: "Guatemala", flag: "🇬🇹" },
  { country: "Guinea", flag: "🇬🇳" },
  { country: "Guyana", flag: "🇬🇾" },
  { country: "Haiti", flag: "🇭🇹" },
  { country: "Honduras", flag: "🇭🇳" },
  { country: "Hong Kong", flag: "🇭🇰" },
  { country: "Hungary", flag: "🇭🇺" },
  { country: "Iceland", flag: "🇮🇸" },
  { country: "India", flag: "🇮🇳" },
  { country: "Indonesia", flag: "🇮🇩" },
  { country: "Iran", flag: "🇮🇷" },
  { country: "Iraq", flag: "🇮🇶" },
  { country: "Ireland", flag: "🇮🇪" },
  { country: "Israel", flag: "🇮🇱" },
  { country: "Italy", flag: "🇮🇹" },
  { country: "Jamaica", flag: "🇯🇲" },
  { country: "Japan", flag: "🇯🇵" },
  { country: "Jordan", flag: "🇯🇴" },
  { country: "Kazakhstan", flag: "🇰🇿" },
  { country: "Kenya", flag: "🇰🇪" },
  { country: "Kuwait", flag: "🇰🇼" },
  { country: "Kyrgyzstan", flag: "🇰🇬" },
  { country: "Laos", flag: "🇱🇦" },
  { country: "Latvia", flag: "🇱🇻" },
  { country: "Lebanon", flag: "🇱🇧" },
  { country: "Lesotho", flag: "🇱🇸" },
  { country: "Liberia", flag: "🇱🇷" },
  { country: "Libya", flag: "🇱🇾" },
  { country: "Lithuania", flag: "🇱🇹" },
  { country: "Luxembourg", flag: "🇱🇺" },
  { country: "Macau", flag: "🇲🇴" },
  { country: "Madagascar", flag: "🇲🇬" },
  { country: "Malawi", flag: "🇲🇼" },
  { country: "Malaysia", flag: "🇲🇾" },
  { country: "Maldives", flag: "🇲🇻" },
  { country: "Mali", flag: "🇲🇱" },
  { country: "Malta", flag: "🇲🇹" },
  { country: "Mauritius", flag: "🇲🇺" },
  { country: "Mexico", flag: "🇲🇽" },
  { country: "Moldova", flag: "🇲🇩" },
  { country: "Monaco", flag: "🇲🇨" },
  { country: "Mongolia", flag: "🇲🇳" },
  { country: "Montenegro", flag: "🇲🇪" },
  { country: "Morocco", flag: "🇲🇦" },
  { country: "Mozambique", flag: "🇲🇿" },
  { country: "Namibia", flag: "🇳🇦" },
  { country: "Nepal", flag: "🇳🇵" },
  { country: "Netherlands", flag: "🇳🇱" },
  { country: "New Zealand", flag: "🇳🇿" },
  { country: "Nicaragua", flag: "🇳🇮" },
  { country: "Niger", flag: "🇳🇪" },
  { country: "Nigeria", flag: "🇳🇬" },
  { country: "Norway", flag: "🇳🇴" },
  { country: "Oman", flag: "🇴🇲" },
  { country: "Pakistan", flag: "🇵🇰" },
  { country: "Palestine", flag: "🇵🇸" },
  { country: "Panama", flag: "🇵🇦" },
  { country: "Papua New Guinea", flag: "🇵🇬" },
  { country: "Paraguay", flag: "🇵🇾" },
  { country: "Peru", flag: "🇵🇪" },
  { country: "Philippines", flag: "🇵🇭" },
  { country: "Poland", flag: "🇵🇱" },
  { country: "Portugal", flag: "🇵🇹" },
  { country: "Qatar", flag: "🇶🇦" },
  { country: "Romania", flag: "🇷🇴" },
  { country: "Russia", flag: "🇷🇺" },
  { country: "Rwanda", flag: "🇷🇼" },
  { country: "Saudi Arabia", flag: "🇸🇦" },
  { country: "Senegal", flag: "🇸🇳" },
  { country: "Serbia", flag: "🇷🇸" },
  { country: "Singapore", flag: "🇸🇬" },
  { country: "Slovakia", flag: "🇸🇰" },
  { country: "Slovenia", flag: "🇸🇮" },
  { country: "South Africa", flag: "🇿🇦" },
  { country: "Spain", flag: "🇪🇸" },
  { country: "Sri Lanka", flag: "🇱🇰" },
  { country: "Sudan", flag: "🇸🇩" },
  { country: "Sweden", flag: "🇸🇪" },
  { country: "Switzerland", flag: "🇨🇭" },
  { country: "Syria", flag: "🇸🇾" },
  { country: "Taiwan", flag: "🇹🇼" },
  { country: "Tajikistan", flag: "🇹🇯" },
  { country: "Tanzania", flag: "🇹🇿" },
  { country: "Thailand", flag: "🇹🇭" },
  { country: "Togo", flag: "🇹🇬" },
  { country: "Tonga", flag: "🇹🇴" },
  { country: "Trinidad and Tobago", flag: "🇹🇹" },
  { country: "Tunisia", flag: "🇹🇳" },
  { country: "Turkey", flag: "🇹🇷" },
  { country: "Turkmenistan", flag: "🇹🇲" },
  { country: "Tuvalu", flag: "🇹🇻" },
  { country: "Uganda", flag: "🇺🇬" },
  { country: "Ukraine", flag: "🇺🇦" },
  { country: "United Arab Emirates", flag: "🇦🇪" },
  { country: "United Kingdom", flag: "🇬🇧" },
  { country: "United States", flag: "🇺🇸" },
  { country: "Uruguay", flag: "🇺🇾" },
  { country: "Uzbekistan", flag: "🇺🇿" },
  { country: "Vanuatu", flag: "🇻🇺" },
  { country: "Vatican City", flag: "🇻🇦" },
  { country: "Venezuela", flag: "🇻🇪" },
  { country: "Vietnam", flag: "🇻🇳" },
  { country: "Yemen", flag: "🇾🇪" },
  { country: "Zambia", flag: "🇿🇲" },
  { country: "Zimbabwe", flag: "🇿🇼" },
];

export default countryCodes;
